title: Data Blog Test
author: Sebastian G
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here I talk about Data Analysis and the courese Im participating in.
  Here I also display my Kaggle projects and other data-related stuff
  im currently busy with.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
